# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - FastAPI1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_ba19578b64bb42afb24f3680b49b5983 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b5e2dcf170f54bc59348384d3102c1fc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ba19578b64bb42afb24f3680b49b5983 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'FastAPI1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0a54385677164a18b7e1b78749bf5230 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ba19578b64bb42afb24f3680b49b5983 }}/appsvc/staticsite:${{ github.sha }}'